import { Project } from "@/types/projects";

// Projects data
export const PROJECTS: Project[] = [
    {
        id: "applysmart",
        title: "ApplySmart",
        description: "An AI-powered resume optimization SaaS platform designed to reverse-engineer ATS tracking systems through secure identity rate-limiting and schema-constrained text transformations.",
        fullDescription: "ApplySmart is an enterprise-grade SaaS platform engineered to help job seekers optimize resumes against target job descriptions in real time. The platform combines a decoupled Next.js and Express.js architecture with secure multi-provider JWT/OAuth authentication pipelines, drag-and-drop file ingestion, and automated multi-container developer environments orchestrated through Docker Compose.",
        image: "/projects/applysmart.png",
        tags: [
            "AWS (EC2, S3, IAM)",
            "Node.js (Express)",
            "Next.js",
            "TypeScript",
            "Docker",
            "Docker Compose",
            "MongoDB Atlas",
            "JWT / OAuth",
            "Zustand",
            "Tailwind CSS"
        ],
        github: "https://github.com/sethnkwo8/ApplySmart",
        live: "https://applysmart.sethnkwo.space",
        featured: true,
        category: "AI SaaS Platform",
        year: "2026",
        role: "Lead Developer",
        challenges: [
            "Mitigated XSS and token-jacking vulnerabilities by engineering an isolated authentication architecture utilizing short-lived JWT access tokens alongside long-lived, strict HttpOnly cookie refresh arrays.",
            "Orchestrated a localized, multi-container architecture using Docker Compose to unify decoupled frontend and backend runtime nodes into an isolated virtual network bridge with unified configuration mappings.",
            "Architected a cross-provider identity reconciliation system that transparently handles multi-provider authentication, automatically linking traditional email registries and Google OAuth accounts on identical address profiles without data fragmentation.",
            "Eliminated client-side hydration lag and synchronized token refresh intervals by structuring a centralized, decoupled global state management store using Zustand.",
            "Designed a secure, fault-tolerant resume ingestion pipeline using a Multer memory-storage engine to restrict incoming file buffering strictly within RAM, avoiding local disk exposure during asynchronous text extraction.",
            "Orchestrated a low-latency AI optimization pipeline integrating gemini-2.5-flash with native JSON schema enforcement, mapping missing semantic tech proficiencies directly to custom aggregated database learning paths.",
            "Designed a scalable identity-based request throttling guard using express-rate-limit to safeguard downstream LLM resource pipelines, using authenticated database object tracking instead of unstable IP-based metrics."
        ],
    },
    {
        id: "allocare",
        title: "Allocare",
        description: "A high-performance financial engine that orchestrates income allocation through secure, containerized architectures, persistent volumes, and asynchronous background workers.",
        fullDescription: "Allocare is a comprehensive full-stack personal finance application built to bridge the gap between passive tracking and intentional budgeting. Utilizing a decoupled Next.js and FastAPI architecture, the system is fully orchestrated with Docker Compose to bind local application microservices seamlessly to an isolated, persistent PostgreSQL database container.",
        image: "/projects/allocare.png",
        tags: [
            "AWS (EC2)",
            "FastAPI (Python)",
            "Next.js",
            "Docker",
            "Docker Compose",
            "PostgreSQL",
            "SQLModel",
            "Resend API",
            "Supabase"
        ],
        github: "https://github.com/sethnkwo8/Allocare",
        live: "https://www.allocare.online/",
        featured: true,
        category: "Full-Stack Web Application",
        year: "2026",
        role: "Lead Developer",
        challenges: [
            "Orchestrated a multi-repo container network using Docker Compose, creating symbolic configuration links to bridge standalone backend `.env` structures directly to the root-level orchestrator without breaking local runtime configurations.",
            "Configured continuous named volume mappings within a local PostgreSQL Docker image container, ensuring seamless host-to-container database state persistence across application lifecycle restarts.",
            "Solved cross-domain authentication drops on mobile Safari by engineering a custom cookie strategy to navigate Intelligent Tracking Prevention (ITP) constraints across isolated production URLs.",
            "Eliminated API latency during onboarding by offloading transactional email delivery to FastAPI BackgroundTasks via the Resend API framework.",
            "Implemented a stateless password recovery system using cryptographically signed tokens (itsdangerous), reducing database bloat and enhancing security boundaries.",
            "Developed a multi-step state machine in Next.js to handle complex user onboarding and currency configuration before final database persistence."
        ],
    },
    {
        id: "gameday-stats",
        title: "Gameday Stats",
        description: "A full-stack football statistics platform delivering live fixtures, standings, player statistics, and automated sports data updates across Europe’s top five leagues.",
        fullDescription: "Gameday Stats is a full-stack sports analytics platform built with Django that aggregates and displays live football data across the Premier League, La Liga, Serie A, Bundesliga, and Ligue 1. The application integrates multiple football APIs to provide real-time fixtures, league standings, team information, and player statistics while leveraging GitHub Actions for automated scheduled data synchronization. Developed as the final project for Harvard’s CS50 Web Programming course, the platform demonstrates large-scale API integration, backend automation workflows, relational database design, and production-style deployment architecture.",
        image: "/projects/gameday-stats.png",
        tags: [
            "Django",
            "Python",
            "PostgreSQL",
            "Bootstrap",
            "JavaScript",
            "API Integration",
            "GitHub Actions",
            "Render"
        ],
        github: "https://github.com/sethnkwo8/Gameday-Stats",
        video: "https://youtu.be/bofClOn7viM",
        featured: true,
        category: "Full-Stack Web Application",
        year: "2025",
        role: "Lead Developer",
        challenges: [
            "Integrated multiple football data providers (API-Football and Football-Data.org) while designing a unified backend structure for fixtures, standings, player statistics, and historical match data.",
            "Engineered automated sports data synchronization workflows using GitHub Actions as an alternative to Celery and Redis due to deployment limitations on Render’s free hosting tier.",
            "Designed and optimized relational PostgreSQL models to efficiently manage leagues, clubs, players, fixtures, standings, and statistics across multiple competitions.",
            "Built scheduled background update pipelines using custom Django management commands to periodically refresh football data without manual intervention.",
            "Implemented responsive sports dashboards and league navigation systems using Bootstrap and custom frontend styling for cross-device usability.",
            "Architected a scalable backend system capable of handling continuously updating sports data while minimizing redundant API requests and maintaining data consistency."
        ],

    },
    {
        id: "bondex-bridge-terminal",
        title: "Bondex Bridge Terminal Website (Client project)",
        description: "A modern corporate website engineered for a logistics and maritime services company with focus on performance, responsiveness, and professional brand presentation.",
        fullDescription: "Bondex Bridge Terminal is a production-ready corporate website built for a logistics and maritime services company to showcase operational capabilities, company information, and contact channels through a clean and modern interface. The project focused heavily on responsive design, reusable architecture, performance optimization, and professional UI implementation using Next.js and Tailwind CSS. The application was deployed with a custom domain using Vercel and Cloudflare DNS configuration.",
        image: "/projects/bondex-bridge.png",
        tags: ["Next.js", "React", "Tailwind CSS", "Vercel", "Cloudflare"],
        github: "",
        live: "https://bondexbridgeterminal.com",
        featured: false,
        category: "Corporate Website",
        year: "2026",
        role: "Frontend Developer",
        challenges: [
            "Designed and implemented a fully responsive corporate interface optimized for mobile, tablet, and desktop experiences.",
            "Built reusable UI components and structured layouts for scalability and maintainability.",
            "Optimized image delivery and loading performance using the Next.js Image component.",
            "Configured production deployment using Vercel alongside Cloudflare DNS management and custom domain integration.",
            "Balanced modern UI aesthetics with accessibility, usability, and fast navigation performance."
        ],

    },
    {
        id: "student-accommodation",
        title: "Student Accommodation Booking Platform (Client Project)",
        description: "A hostel booking and accommodation management platform featuring online reservations, payment processing, admin workflows, and automated email notifications.",
        fullDescription: "StayEase is a Flask-based hostel booking management system designed to streamline room reservations, booking management, and payment processing for accommodation businesses. The application enables users to browse rooms, make secure bookings, process payments through Paystack, and receive automated email confirmations. An administrative dashboard provides tools for approving, activating, cancelling, and managing bookings while automatically updating room availability in real time.",
        image: "/projects/student-accommodation.jpeg",
        tags: ["Flask", "Python", "SQLite", "Bootstrap", "Paystack API", "Flask-Login", "SMTP"],
        github: "https://github.com/sethnkwo8/Student-Accommodation",
        video: "https://youtu.be/KalpQyaUkQg",
        featured: false,
        category: "Full-Stack Web Application",
        year: "2025",
        role: "Full Stack Developer",
        challenges: [
            "Integrated Paystack payment processing for secure online booking transactions.",
            "Implemented automated room inventory synchronization based on booking approval and cancellation workflows.",
            "Built an admin management dashboard for handling users, bookings, and room management operations.",
            "Configured SMTP email notification pipelines for booking confirmations, approvals, and cancellations.",
            "Designed a role-based authentication system using Flask-Login for secure administrative access."
        ],
    },
    {
        id: "personal-finance-api",
        title: "Personal Finance API",
        description: "A secure, containerized RESTful API gateway built for modern accounting platforms with structured query parameters and compound index database performance tuning.",
        fullDescription: "A production-ready RESTful API for managing personal finances, built with Node.js, Express, TypeScript, and MongoDB. This project demonstrates high-performance backend engineering standards including container runtime isolation, advanced request filtration, automated integration test suites, and strict user data security structures.",
        image: "/projects/personal-finance.png",
        tags: [
            "Node.js (Express)",
            "TypeScript",
            "Docker",
            "Docker Compose",
            "MongoDB",
            "JWT Authentication",
            "Zod",
            "Jest"
        ],
        github: "https://github.com/sethnkwo8/Personal-Finance-API",
        featured: false,
        category: "Backend API",
        year: "2026",
        role: "Backend Developer",
        challenges: [
            "Containerized the development application environment using multi-stage Docker builds to establish immediate architecture isolation and achieve automated hot-reloading through bind-mount sync loops.",
            "Designed an efficient filtering and pagination system that supports multiple query parameters (category, amount range, date range) while maintaining query performance at scale.",
            "Optimized database queries using MongoDB indexing strategies (compound indexes on userId, createdAt, category) to prevent full collection scans and minimize query retrieval windows.",
            "Implementing a secure authentication system using JWT with access and refresh tokens, including token lifecycle management and protected route handling.",
            "Designing a clean and scalable backend architecture (controllers, services, models) to separate concerns and maintain code readability as the project grows.",
            "Building a centralized error handling system to consistently manage validation, authentication, and database errors across all endpoints.",
            "Ensuring strict user data isolation so authenticated users can only access and modify their own resources.",
            "Implementing robust request validation for both body and query parameters using Zod, including type coercion and edge-case handling.",
            "Securing the API with middleware such as rate limiting and HTTP security headers to mitigate common attack vectors.",
            "Writing reliable integration tests using Jest and Supertest while managing database state between tests to avoid flaky results."
        ]
    },
    {
        id: "task-manager-api",
        title: "Task Manager API",
        description: "A secure RESTful task management API built with Django REST Framework featuring JWT authentication, filtering, testing, and production-style backend architecture.",
        fullDescription: "Task Manager API is a backend-focused REST API designed for secure and scalable task management. Built using Django REST Framework and JWT authentication with SimpleJWT, the platform allows users to register, authenticate, and manage personal task lists through a fully protected API architecture. The project includes advanced filtering, searching, pagination, automated user-task isolation, comprehensive API testing, and PostgreSQL database integration to simulate a production-ready backend environment.",
        image: "/projects/task-manager.png",
        tags: ["Django", "Django REST Framework", "PostgreSQL", "JWT", "SimpleJWT", "Python"],
        github: "https://github.com/sethnkwo8/Task-Manager-API",
        featured: false,
        category: "Backend API",
        year: "2025",
        role: "Backend Developer",
        challenges: [
            "Implemented secure JWT authentication flows using SimpleJWT and protected route architecture.",
            "Designed automatic user-task association logic ensuring users only accessed their own data.",
            "Built reusable DRF ModelViewSets with advanced filtering, searching, and pagination support.",
            "Structured comprehensive API test coverage using APITestCase for authentication and CRUD operations.",
            "Configured PostgreSQL persistence and environment-based configuration management for production-style deployment readiness."
        ],

    },
    {
        id: "gymtroll",
        title: "GYMTROLL",
        description: "A fitness-focused workout planning platform that generates personalized workout routines, nutrition guidance, and fitness tools for users.",
        fullDescription: "GYMTROLL is a workout and fitness web application built to help users create structured workout plans tailored to their goals, workout preferences, and physical targets. The platform generates personalized workout routines based on user inputs such as fitness goals, workout frequency, preferred training environment, and weight targets. Additional features include workout exercise libraries, nutrition guidance, BMI calculation tools, and educational resources for users beginning their fitness journey.",
        image: "/projects/gymtroll.jpeg",
        tags: ["Flask", "Python", "SQLite", "Bootstrap", "HTML", "CSS", "JavaScript"],
        github: "https://github.com/sethnkwo8/GymTroll",
        video: "https://youtu.be/D919CVIKqnA",
        featured: false,
        category: "Full-Stack Web Application",
        year: "2024",
        role: "Full Stack Developer",
        challenges: [
            "Developed a personalized workout recommendation engine based on multiple user fitness criteria.",
            "Implemented user authentication and session management for personalized plan persistence.",
            "Built a structured workout library containing guided exercise resources and video integrations.",
            "Integrated BMI calculation tools and nutrition education systems to enhance the overall fitness experience.",
            "Designed flexible plan cancellation and regeneration flows to accommodate changing user fitness goals."
        ],
    },
    {
        id: "tradecalc",
        title: "TradeCalc",
        description: "A desktop trading calculator application built for profit analysis, risk management, compounding simulations, and trading performance visualization.",
        fullDescription: "TradeCalc is a Python-based trading calculator application developed to help traders perform profit calculations, evaluate risk strategies, and simulate compound growth scenarios through a clean desktop interface. The platform supports multiple trading modes including standard profit calculations, compounding strategies, growth-rate analysis, stop-loss planning, take-profit analysis, and reward-to-risk ratio calculations. Additional functionality includes trade history export to CSV files and profit visualization using interactive charts.",
        image: "/projects/tradecalc.png",
        tags: ["Python", "CustomTkinter", "Matplotlib", "CSV", "Desktop Application"],
        github: "https://github.com/sethnkwo8/TradeCalc",
        video: "https://youtu.be/oBtbOppqQcg",
        featured: false,
        category: "Desktop Application",
        year: "2025",
        role: "Software Developer",
        challenges: [
            "Engineered multiple trading calculation engines supporting compounding, growth-rate, and risk-management strategies.",
            "Built a desktop GUI using CustomTkinter to improve usability and workflow navigation.",
            "Integrated chart visualization with Matplotlib for graphical profit and growth analysis.",
            "Implemented CSV export functionality for automated trade history tracking and persistence.",
            "Designed validation systems to prevent incorrect or invalid trading calculations during user interaction."
        ],
    },
]