import { Project } from "@/types/projects";

// Projects data
export const PROJECTS: Project[] = [
    {
        id: "allocare",
        title: "Allocare",
        description: "A high-performance financial engine that orchestrates income allocation through secure, stateless architecture and asynchronous processing.",
        fullDescription: "Allocare is a comprehensive personal finance application built to bridge the gap between passive tracking and intentional budgeting. By utilizing a decoupled Next.js and FastAPI architecture, the platform provides real-time insights into budget allocations (Needs, Wants, Savings) while maintaining strict security and zero-latency user experiences.",
        image: "/projects/allocare.png",
        tags: ["Next.js", "FastAPI", "PostgreSQL", "SQLModel", "Resend API"],
        github: "https://github.com/sethnkwo8/Allocare",
        live: "https://www.allocare.online/",
        featured: true,
        category: "Full-Stack Web Application",
        year: "2026",
        role: "Lead Developer",
        challenges: [
            "Solved cross-domain authentication drops on mobile Safari by engineering a custom cookie strategy to navigate Intelligent Tracking Prevention (ITP) constraints.",
            "Eliminated API latency during onboarding by offloading transactional email delivery to FastAPI BackgroundTasks via the Resend API.",
            "Implemented a stateless password recovery system using cryptographically signed tokens (itsdangerous), reducing database bloat and enhancing security.",
            "Architected a strictly typed, decoupled infrastructure between a Vercel-hosted frontend and a Railway-hosted FastAPI backend.",
            "Developed a multi-step state machine in Next.js to handle complex user onboarding and currency configuration before final database persistence."
        ],
    },
    {
        id: "gameday-stats",
        title: "Gameday Stats",
        description: "Django web application that gives you updated match results, standings, info and player details for Europe's top 5 football leagues.",
        fullDescription: "Gameday Stats is a full-stack web application built with Django that provides live football (soccer) data — including fixtures, scores, standings, and player statistics — for the top five European leagues",
        image: "/projects/gameday-stats.png",
        tags: ["JavaScript", "Django", "Render", "PostgreSQL", "External APIs"],
        github: "https://github.com/sethnkwo8/Gameday-Stats",
        video: "https://youtu.be/bofClOn7viM",
        featured: true,
        category: "Full-Stack Web Application",
        year: "2025",
        role: "Lead Developer",
        challenges: [
        ],
    },
    {
        id: "bondex-bridge",
        title: "Bondex Bridge Terminal Website (Client project)",
        description: "A modern corporate website built for a logistics and maritime services company.",
        fullDescription: "A responsive business website designed to present company services, contact information, and operational capabilities in a clean and professional layout. Developed as a client project with focus on performance, usability, and modern UI design.",
        image: "/projects/bondex-bridge.png",
        tags: ["Next.js", "Tailwind CSS", "Vercel", "Cloudflare"],
        github: "https://github.com/sethnkwo8/Bondex-Bridge",
        live: "https://www.bondexbridgeterminal.com",
        featured: true,
        category: "Web Application",
        year: "2026",
        role: "Lead Developer",
        challenges: [
        ],
    },
    {
        id: "student-accommodation",
        title: "Student Accommodation Booking Platform (Client Project)",
        description: "Student Accommodation Flask Web Application.",
        fullDescription: "StayEase is a Flask-based Hostel & Accommodation Booking System that allows users to book rooms, make payments, and receive email confirmations.",
        image: "/projects/student-accommodation.jpeg",
        tags: ["Flask", "CSS", "JavaScript", "SQLite", "Paystack API"],
        github: "https://github.com/sethnkwo8/Student-Accommodation",
        video: "https://youtu.be/KalpQyaUkQg",
        featured: false,
        category: "Full-Stack Web Application",
        year: "2025",
        role: "Lead Developer",
        challenges: [
        ],
    },
    {
        id: "personal-finance-api",
        title: "Personal Finance API",
        description: "API Personal Finance Project using Node.js, MongoDB + TypeScript",
        fullDescription: "A RESTful API for managing personal finances, built with Node.js, Express, TypeScript, and MongoDB. Includes authentication, expense tracking, filtering, pagination, and structured error handling.",
        image: "/projects/personal-finance.png",
        tags: ["Node.js (Express)", "MongoDB", "TypeScript", "JWT authentication", "Jest"],
        github: "https://github.com/sethnkwo8/Personal-Finance-API",
        featured: false,
        category: "REST API",
        year: "2026",
        role: "Lead Developer",
        challenges: [
            "Designing an efficient filtering and pagination system that supports multiple query parameters (category, amount range, date range) while maintaining query performance at scale.",
            "Optimizing database queries using MongoDB indexing strategies (compound indexes on userId, createdAt, category) to prevent full collection scans and improve response times.",
            "Implementing a secure authentication system using JWT with access and refresh tokens, including token lifecycle management and protected route handling.",
            "Handling MongoDB ObjectId conversions safely between TypeScript and Mongoose to avoid runtime errors and ensure type consistency across the application.",
            "Designing a clean and scalable backend architecture (controllers, services, models) to separate concerns and maintain code readability as the project grows.",
            "Building a centralized error handling system to consistently manage validation, authentication, and database errors across all endpoints.",
            "Ensuring strict user data isolation so authenticated users can only access and modify their own resources.",
            "Implementing robust request validation for both body and query parameters using Zod, including type coercion and edge-case handling.",
            "Securing the API with middleware such as rate limiting and HTTP security headers to mitigate common attack vectors.",
            "Writing reliable integration tests using Jest and Supertest while managing database state between tests to avoid flaky results."
        ]
    },
    {
        id: "task-manager-api",
        title: "Task Manager API",
        description: "API Task Manager Project using Django's REST Framework",
        fullDescription: "A secure and fully-featured Task Management REST API built with Django REST Framework (DRF) and JWT Authentication (SimpleJWT). Users can register, log in, and manage their personal task lists — including creating, updating, searching, and deleting tasks.",
        image: "/projects/task-manager.png",
        tags: ["Django", "Django REST Framework", "PostgreSQL", "SimpleJWT"],
        github: "https://github.com/sethnkwo8/Task-Manager-API",
        featured: false,
        category: "REST API",
        year: "2025",
        role: "Lead Developer",
        challenges: [
        ],
    },
    {
        id: "gymtroll",
        title: "GymTroll",
        description: "This is a web application for a gym website that aids users on their workout journey.",
        fullDescription: "Gymtroll is a workout web application that helps users start their workout journey to get to their ideal or dream body goal and aid them in their fitness journey.",
        image: "/projects/gymtroll.jpeg",
        tags: ["Flask", "CSS", "JavaScript", "SQLite", "Bootstrap"],
        github: "https://github.com/sethnkwo8/GymTroll",
        video: "https://youtu.be/D919CVIKqnA",
        featured: false,
        category: "Full-Stack Web Application",
        year: "2025",
        role: "Lead Developer",
        challenges: [
        ],
    },
    {
        id: "tradecalc",
        title: "TradeCalc",
        description: "TradeCalc is a Python-based trading calculator designed for quick and accurate trade planning.",
        fullDescription: "This is a Trading Calculator written in Python. It helps traders calculate Stop-Loss, Take Profit, Reward-Risk ratio and has a feature for Deriv Accumulator calculations.",
        image: "/projects/tradecalc.png",
        tags: ["Python", "CustomTkinter", "Matplotlib", "CSV Module"],
        github: "https://github.com/sethnkwo8/TradeCalc",
        video: "https://youtu.be/oBtbOppqQcg",
        featured: false,
        category: "Desktop App",
        year: "2025",
        role: "Lead Developer",
        challenges: [
        ],
    },
]